//회원가입(1)
###
POST http://localhost:3000/api/users/
Content-Type: application/json 

{
  "email": "test@example.com",
  "name": "유택",
  "password": "1234abcd!",
  "type": "BUYER",
  "image": null
}

//회원가입(2)
###
POST http://localhost:3000/api/users/
Content-Type: application/json 

{
  "email": "test3@example.com",
  "name": "도하가",
  "password": "1234abcd24!",
  "type": "SELLER",
  "image": null
}


###
POST http://localhost:3000/api/auth/login
Content-Type: application/json 
  
{
  "email": "test@example.com", 
  "password": "1234abcd!"
}

###
POST http://localhost:3000/api/auth/logout
Content-Type: application/json  

//내정보보 조회
###
GET http://localhost:3000/api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNtY2EzZnRvYzAwMDFvYmFidjZ4ZWJvZmwiLCJpYXQiOjE3NTA3NDk4ODYsImV4cCI6MTc1MDc1MzQ4Nn0.lt33g0WtbwMZCeU_k3FVcJMvOKhL5O01rLnpDgYhaOE


###
PATCH http://localhost:3000/api/users//me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNtY2EzZnRvYzAwMDFvYmFidjZ4ZWJvZmwiLCJpYXQiOjE3NTA3NDk4ODYsImV4cCI6MTc1MDc1MzQ4Nn0.lt33g0WtbwMZCeU_k3FVcJMvOKhL5O01rLnpDgYhaOE

{
  "name": "유택킹",
  "image": "https://new.image.link",
  "currentPassword": "1234abcd!",
  "password": "new1234"
}
 
