login:
  post:
    tags: [Auth]
    summary: 로그인
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/LoginRequest'
    responses:
      '201':
        description: 로그인 성공
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginResponse'
      '400':
        description: 잘못된 요청
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ErrorResponse'
      '401':
        description: 인증 실패(이메일/비밀번호 오류)
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ErrorResponse'
refresh:
  post:
    tags: [Auth]
    summary: 토큰 재발급
    responses:
      '200':
        description: 토큰 재발급 성공
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshResponse'
      '400':
        description: 잘못된 요청/리프레시 토큰 없음
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ErrorResponse'
      '401':
        description: 인증 실패/유효하지 않은 토큰
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ErrorResponse'
logout:
  post:
    tags: [Auth]
    summary: 로그아웃
    security:
      - bearerAuth: []
    responses:
      '200':
        description: 로그아웃 성공
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LogoutResponse'
      '401':
        description: 인증 실패
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ErrorResponse'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
        password:
          type: string
    LoginResponse:
      type: object
      properties:
        user:
          type: object
        accessToken:
          type: string
    RefreshResponse:
      type: object
      properties:
        accessToken:
          type: string
    LogoutResponse:
      type: object
      properties:
        message:
          type: string
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
